import { test, expect } from '@playwright/test'

test('all mapped buildings share a navigable campus and context is not audit evidence', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('.campus-building')).toHaveCount(231)
  await expect(page.locator('[data-campus-boundary]')).toHaveCount(1)
  await expect(page.locator('[data-road-id]')).toHaveCount(229)
  const world=page.locator('[data-world-transform]')
  const initial=await world.getAttribute('transform')
  const map=page.getByRole('group',{name:/Geographic IIT Roorkee campus model/})
  await map.focus()
  await page.keyboard.press('ArrowRight')
  await expect(world).not.toHaveAttribute('transform',initial!)
  await page.getByRole('button',{name:'Reset campus',exact:true}).click()
  await expect(world).toHaveAttribute('transform',initial!)
  const rect=await map.boundingBox()
  await page.mouse.move(rect!.x+rect!.width*.35,rect!.y+rect!.height*.6)
  await page.mouse.down()
  await page.mouse.move(rect!.x+rect!.width*.35+60,rect!.y+rect!.height*.6+35,{steps:6})
  await page.mouse.up()
  await expect(world).not.toHaveAttribute('transform',initial!)
  await page.getByRole('button',{name:'Reset campus',exact:true}).click()
  await page.getByRole('button',{name:'Show building list',exact:true}).click()
  const list=page.locator('.index-popover')
  await expect(list.locator('.index-row')).toHaveCount(231)
  await list.getByRole('combobox',{name:'Building type',exact:true}).selectOption('Audit scope')
  await expect(list.locator('.index-row')).toHaveCount(12)
  await list.getByRole('combobox',{name:'Building type',exact:true}).selectOption('All buildings')
  await list.getByRole('textbox',{name:'Search buildings',exact:true}).fill('Thomason')
  await list.locator('.index-row').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.evidence-content h2')).toHaveText('James Thomason Building')
  await expect(page.locator('.context-evidence')).toContainText('Not audited')
  await expect(page.locator('.context-evidence .case-card')).toHaveCount(0)
  await expect(page.locator('.campus-building')).toHaveCount(231)
  await page.getByRole('button',{name:'Focus selected building',exact:true}).click()
  await expect(world).toHaveAttribute('transform',/scale\(4\)/)
  await expect(page.getByRole('button',{name:'Focus selected building',exact:true})).toHaveAttribute('aria-pressed','true')
  await page.screenshot({path:'artifacts/designs/geographic-main-focused.png',fullPage:true})
  await page.getByRole('button',{name:'Zoom in',exact:true}).click()
  await expect(world).toHaveAttribute('transform',/scale\(5\.6\)/)
  await page.getByRole('button',{name:'Reset campus',exact:true}).click()
  await expect(world).toHaveAttribute('transform',initial!)
})

test('current campus source data is publicly reproducible', async ({request}) => {
  const response=await request.get('/campus/manifest.json')
  expect(response.ok()).toBe(true)
  const manifest=await response.json()
  expect(manifest.statistics).toMatchObject({buildings:231,auditBuildings:12,roads:229,surfaces:47,trees:17})
  expect(manifest.license).toBe('ODbL-1.0')
  expect(manifest.diagnostics).toEqual([])
  const chunks=await Promise.all(Array.from({length:5},(_,i)=>request.get('/campus/buildings-'+i+'.json').then(r=>r.json())))
  expect(chunks.flat()).toHaveLength(231)
  expect(chunks.flat().find(b=>b.id==='govind').rings.some((r:{role:string})=>r.role==='inner')).toBe(true)
})
